// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDndSNLzhMuhHfZdS6y54j8rhdNLveQz68',
    appId: '1:340340771153:web:b01deec1277a2c21602b70',
    messagingSenderId: '340340771153',
    projectId: 'my-portfolio-79071',
    authDomain: 'my-portfolio-79071.firebaseapp.com',
    storageBucket: 'my-portfolio-79071.firebasestorage.app',
    measurementId: 'G-S0DY69FY4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7lbgvQ5T3uGAUBbY7Tbl_zsvCWPUeTUM',
    appId: '1:340340771153:android:e0565ff2201e02c7602b70',
    messagingSenderId: '340340771153',
    projectId: 'my-portfolio-79071',
    storageBucket: 'my-portfolio-79071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUhw9elZKjqBUpbvCtxDvisb0X8fHElHA',
    appId: '1:340340771153:ios:becd1aeed6570c3b602b70',
    messagingSenderId: '340340771153',
    projectId: 'my-portfolio-79071',
    storageBucket: 'my-portfolio-79071.firebasestorage.app',
    iosBundleId: 'com.example.callExecutive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUhw9elZKjqBUpbvCtxDvisb0X8fHElHA',
    appId: '1:340340771153:ios:becd1aeed6570c3b602b70',
    messagingSenderId: '340340771153',
    projectId: 'my-portfolio-79071',
    storageBucket: 'my-portfolio-79071.firebasestorage.app',
    iosBundleId: 'com.example.callExecutive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDndSNLzhMuhHfZdS6y54j8rhdNLveQz68',
    appId: '1:340340771153:web:84f74b276823421b602b70',
    messagingSenderId: '340340771153',
    projectId: 'my-portfolio-79071',
    authDomain: 'my-portfolio-79071.firebaseapp.com',
    storageBucket: 'my-portfolio-79071.firebasestorage.app',
    measurementId: 'G-8GESELNQJ9',
  );
}
